@echo off
echo FitLife AI Baslatiliyor...
cd /d "%~dp0"
echo Sunucu aktif ediliyor...
echo Tarayici 4 saniye icinde acilacak...
start cmd /c "timeout /t 4 >nul & start http://127.0.0.1:3000"
call npm run dev
pause
